### PR TITLE
Flood Extent Enhancement

### PR DESCRIPTION
**Pull request by fastnish**
**Changes**

Two changes were made to pixel_counter.py and pixel_counter_functions.py:

Within pixel_counter.py, a new function was added: make_flood_extent_polygon.

- This function converts the input inundation extent raster to a polygon 
- The output file is then fed into the main pixel counter function.

Within pixel_counter_functions.py, the method of counting and output column headers were modified.

- Only the NLCD pixel counts of inundated regions are returned in the output .csv file
- Columns are renamed  "_f_NLCDValue_" to avoid confusion with the pixel counts for the total catchment. 

**Input Requirements**:
- Inundation Extent in .tif format with inundated regions given positive HydroIDs and non inundated areas given negative HydroIDs
- Rasterized NLCD Layer 

Output: CSV file displaying the number of NLCD pixels per catchment within the flood extent

**Testing**
Tested on sample files:

A sample inundation extent  100_0_ms_inund_extent_12090301.tif
A national NLCD dataset: nlcd_2019_land_cover_l48_20210604.img 

The output CSV file shows NLCD pixels within the inputed flooded boundaries categorized by land cover type grouped by catchment HydroID
[myCSV22.csv](https://github.com/BradfordBates-NOAA/catchment-enricher/files/8473026/myCSV22.csv)

### CODE REVIEW

**Comment by BradfordBates-NOAA** [comment]
Hey Nish, it looks like there are a few merge conflicts that need to be resolved. Do you got it or would you like to tag up?

**Comment by BradfordBates-NOAA** [comment]
@fastnish, also please update the Labels and Project attributes on this PR.

**Comment by fastnish** [comment]
> Hey Nish, it looks like there are a few merge conflicts that need to be resolved. Do you got it or would you like to tag up?

I'll take a look at it and if I can't figure it out, I'll reach out!

**Comment by fastnish** [comment]
> @fastnish, also please update the Labels and Project attributes on this PR.

Will do! Remind me, what are attributes again?

**Comment by fastnish** [comment]
@BradfordBates-NOAA  all the conflicts looked to be some small addition/modification I made to the original. Seemed fine to me!

**Comment by BradfordBates-NOAA** [comment]
At the top right of the PR, you can specific labels and associate this PR with our project

**Comment by fastnish** [comment]
done!

**Comment by BradfordBates-NOAA** [comment]
@fastnish Please add a description to this PR about what the enhancement does. You can simply edit your first comment/description. It doesn't have to be very lengthy, but pretend you're writing to a different developer or yourself in the future. For example, check out this one: https://github.com/BradfordBates-NOAA/catchment-enricher/pull/19

**Pull request merged**
